# Generated by Django 3.2 on 2024-06-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Costo')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(verbose_name='Numero')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='Numero de asiento')),
                ('occupied', models.BooleanField(verbose_name='Ocupado')),
                ('screen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refence', models.CharField(max_length=250, verbose_name='Referencia')),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('seat', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.seat')),
            ],
        ),
    ]
