# Generated by Django 3.2 on 2024-06-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('duration', models.IntegerField()),
                ('starring', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
