# Generated by Django 3.2 on 2024-06-09 10:47

import auth_user.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('last_name2', models.CharField(max_length=255, null=True, verbose_name='Segundo Apellido ')),
                ('picture', models.ImageField(blank=True, default=None, upload_to=auth_user.models.Customer.custom_upload_to, verbose_name='Foto')),
                ('gender', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=150, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
